tools: Add Vulkan SC variant of vulkaninfo
KhronosGroup/VulkanSC-Tools pull request #10
Opened 2023-12-15 15:06 UTC by aqnuep

2024-01-04 21:26 UTC, dgkoch requested changes

2024-01-04 21:26 UTC, dgkoch commented on vulkaninfo/vulkaninfo.h
>          err = ext_funcs.vkCreateDebugReportCallbackEXT(instance, &dbg_info, nullptr, &debug_callback);
dbg_info is still unconditionally chained into VkInstanceCreateInfo above here - this is an unknown structure in VKSC.

2024-01-04 21:26 UTC, dgkoch commented on output.txt
> +Vulkan SC Instance Version: 1.0.13
Good to see the sample output, but is this file supposed to be checked in?

2024-01-05 00:09 UTC, sricker-nvidia commented
I tested on linux after fixing the vkCreateDebugReportCallbackEXT issue mentioned by Daniel, but hit another issue where the VkDeviceCreateInfo structure is missing mandatory structures like VkDeviceObjectReservationCreateInfo in its pNext chain. Haven't investigate further past that issue.

2024-01-05 01:48 UTC, dgkoch commented
@aqnuep seems like you need to run this with VVL :-)

2024-01-05 13:27 UTC, aqnuep commented
> @aqnuep seems like you need to run this with VVL :-)

Indeed. I guess my validation setup when running it was incorrect. I'll re-check everything.

2024-01-05 14:45 UTC, aqnuep commented
@sricker-nvidia, could you give it a go with the updates? It is now certainly validation-clear.

2024-01-05 15:16 UTC, dgkoch approved these changes

2024-01-05 15:16 UTC, dgkoch commented
LGTM pending Sam's testing results.

2024-01-08 21:47 UTC, sricker-nvidia commented
Just finished testing the latest version of the patch on L4T / embedded linux and QNX. Working as expected on both.

LGTM

2024-01-09 10:24 UTC, aqnuep commented
Thanks, @sricker-nvidia!

2024-01-10 10:01 UTC, merged